#!/bin/bash

# Запускаем сортировку импортов
make sort

# Запускаем линтер
make lint-fast
if [ $? -ne 0 ]; then
  echo "Linting failed. Push aborted."
  exit 1
fi

# Если до этого этапа ошибок не было, разрешаем пуш
exit 0