services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: go-shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis: 
    image: redis:latest
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: ProdDockerfile
    ports:
      - 8080:8080
    networks:
      - backend-network
    depends_on:
      - db
      - redis
  dendrite:
    image: matrixdotorg/dendrite-monolith:latest
    container_name: dendrite
    volumes:
      - ./dendrite_config.yaml:/etc/dendrite/dendrite.yaml:ro
      - ./dendrite_matrix_key.pem:/etc/dendrite/matrix_key.pem:ro
      - dendrite_data:/var/dendrite
    networks:
      - backend-network
    command: --config /etc/dendrite/dendrite.yaml --really-enable-open-registration
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  dendrite_data:
